include: _default_template_yaml
task: mvp_intuitive_physics 
dataset_name: intuitive_physics
test_split: full 
metric_list:
  - metric: pair_accuracy
    aggregation: !function utils.mvp_ip_pair_accuracy
    higher_is_better: true
  - metric: single_accuracy
    aggregation: !function utils.mvp_single_accuracy
    higher_is_better: true
